#ask player age and name
y = input("Enter Your Name : ")
x = int(input("Enter you age : "))
if x > 18 : #check player age
    PlayerChoice = None
    PlayerChoices = ["dirty","fice","funny","office"]
    print("dirty  fice   funny office ")
    while PlayerChoice not in PlayerChoices :
     PlayerChoice = input("What mad lab if you want to play ? ")
     if "dirty" in PlayerChoice:
        FeelingState = input("Enter a feeling state : ")
        SelfSexAct = input("Enter a self-sex act : ")
        SelfSexualActVerb = input("Enter a sexual-act-verb : ")
        Action = input("Enter a action/feeling response to pleasure : ")
        SelfSexualActVerb2 = input("Enter a sexual act-verb : ")
        GenderNoun = input("Enter a gender noun : ")
        BodyPart = input("Enter a body part : ")
        Orifice = input("Enter a orifice : ")
        BodyPart2 = input("Enter a body part : ")
        Orife2 = input("Enter a orife : ")
        PlayfulAct = input("Enter a Playful act : ")
        Adjective = input("Enter a adjective : ")
        NameOfGenital = input("Enter a name of genital : ")
        SexyObject = input("Enter a sexy object : ")
        SexyActionWord = input("Enter a sexy action word : ")
        Adjective2 = input("Enter a adjcetive2")
        Verb = input("Enter a verb : ")
        Exclamation = input("Enter a exclamation : ")
        Adjective3 = input("Enter a adjective : ")
        

        print(" I feel so "+ FeelingState + ".I was "+SelfSexAct+" this morning and I was fantasizing about how I'd love if you'd "+SelfSexualActVerb+" me; that would really make me "+Action+" and I'd want to "+SelfSexualActVerb+" all night long.What I'd really love is to see you with a "+GenderNoun+".What is would do to me to see you put you "+BodyPart+" in hir "+Orifice+" hir "+BodyPart2+" in your"+Orife2+" you "+PlayfulAct+" and lots of "+Adjective+" kissing.I was wondering about your "+NameOfGenital+".Does it need or want for anything? Need me to scratch an itch? To lick it like a "+SexyObject+" ? I would love to "+SexyActionWord+" you.I want to explore your most "+Adjective2+" fantasy.if you'd "+Verb+" me."+Exclamation+"!I want you.I want you bad.So anyway.give me a call back.I'd love to make a "+Adjective3+" date very very soon.")
     PlayerChoice2 = None
    PlayerChoices2 = ["fice","funny","office"]
    print(" fice   funny office")
    while PlayerChoice2 not in PlayerChoices2 :
        PlayerChoice2 = input("What mad lib if you want to play ? ")
        if "fice" in PlayerChoice2:
            Noun = input("Enter a noun : ")
            Adjective4 = input("Enter a Adjective : ")
            Noun2 = input("Enter a noun : ")
            Adjective5 = input("Enter a Adjective : ")
            Noun3 = input("Enter a Noun : ")
            Verb = input("Enter a verb : ")
            Adjective6 = input("Enter a adjective : ")
            Noun4 = input("Enter a noun : ")
            Noun5 = input("Enter a noun : ")
            Adjective7 = input("Enter a adjective : ")
            Noun6 = input("Enter a noun : ")

            print("Hello there, fellow studnets of Meridian Elementary school.This is where you get to be creative, put in wacky phrases, and have fun! Today, you will be interviewing our school mascot,Thunder. Enjoy!")
            print("Lauren: Thunder, have you experienced some "+ Noun + " kids in your "+Adjective4+" career ? ")
            print("How does is feel to be the most "+Adjective5+" person in the "+Noun3)
            print("It definitely gets me "+Verb+"!")
            print("Do you like your "+Adjective6+" career ?")
            print("Yes,I do.I see "+Noun4+" learning every "+Noun5+".")
            print("Well we are "+Adjective7+" to "+Noun6+" that!")
        if "funny" in PlayerChoice2:
            Adjective8 = input("Enter a adjective : ")
            FirstName = input("Enter a first name : ")
            PastTenseVerb = input("Enter a past tense verb : ")
            FirstName2 = input("Enter a first name : ")
            Adjective9 = input("Enter a Adjective : ")
            Adjective10 = input("Enter a adjective : ")
            PluralNoun = input("Enter a plural noun : ")
            LargeAnimal = input("Enter a large animal : ")
            SmallAnimal = input("Enter a small animal : ")
            AgirlName = input("Enter a girl name : ")
            Adjective11 = input("Enter a adjective : ")
            PluralNoun2 = input("Enter a plural Noun : ")
            Adjective12 = input("Enter a adjective : ")
            PluralNoun3 = input("Enter a plural noun : ")
            Number = int(input("Enter number 1-50 : "))
            FirstName3 = input("Enter first name's : ")
            NUmber2 = int(input("Enter a Number : "))
            PluralNoun4 = input("Enter a plural noun : ")
            Number3 = input("Enter a number : ")
            PluralNoun5 = input("Enter a plural noun : ")

            print("I, the "+Adjective8+"and"+Adjective9+FirstName+"has"+PastTenseVerb+FirstName+"s"+Adjective9+" sister and plans to steal her "+Adjective10+PluralNoun+"! What are a "+LargeAnimal+" and backpacking "+SmallAnimal+" Before you can help "+AgirlName+", you'll have to collect the "+Adjective11+PluralNoun2+" and "+Adjective12+PluralNoun3+" that open up the "+Number+" worlds connected to a "+FirstName3+" lair. There are "+NUmber2+PluralNoun4+" and "+Number3+PluralNoun5+" in the game,along with hundredes of other goodies for you to find.")

        if "office" in PlayerChoice2:
            ArticleOfClothing = input("Enter a article of clothing : ")
            Superlative = input("Enter a superlative : ")
            PluralNoun6 = input("Enter a plural noun : ")
            Sprot = input("Enter a sport : ")
            Noun7 = input("Enter a noun : ")
            PersonalTitle = input("Enter a personal title  : ")
            Adverb = input("Enter a adverb : ")
            ProperNoun = input("Enter proper noun : ")
            SongTitle = input("Enter a song title : ")
            Interjection = input("Enter a Interjection : ")
            ArticleOfClothing2 = input("Enter Article of clothing : ")
            Verb2 = input("Enter a verb : ")
            FamousPerson = input("Enter Famous person : ")
            PluralNoun7 = input("Enter a plural noun : ")
            PluralNoun8 = input("Enter a plural noun : ")
            ArticleOfClothing3 = input("Enter a article of clothing : ")
            Adjective13 = input("Enter a adjective : ")
            FieldOfStudy = input("Enter filed of study : ")

            print("I scoured my closet for the perfect "+ArticleOfClothing+" to wear.Dressing for the "+Superlative+" place around isn't easy.Sweating "+PluralNoun6+" during the interview is a sure sign of weakness. I must remember to play up my strength: "+Sprot+",menacing stares,and "+Noun7+" collecting.It has always been my dream to work with the Angel of Death, or "+PersonalTitle+" Devil.The power and prestige are "+Adverb+" Desirable.The Gates of "+ProperNoun+" tower above me as I ring the doorbell. I can't belive "+SongTitle+" is the doorbell chime."+Interjection+".his back "+ArticleOfClothing2+" looks better in person!")
            print("The Devil : Welcome to Hell. Your Interview will "+Verb2+" now.")
            print("Me : It's a pleasure to meet you. My name is "+FamousPerson+".")
            print("The Devil: Who cares? I have only one question. Do you hate "+PluralNoun7+" ?")
            print("Me : Yes,yes I do.I hate them more than "+PluralNoun8+".")
            print("The Devil: Your're hired.Wait,is that a "+ArticleOfClothing3+"you're wearing ? ")
            print("Me : No,it's actually a "+Adjective13+" suit.")
            print("The Devil: You're fired.Maybe you should pursue a career in "+FieldOfStudy+".")    
else:
    PlayerChoice2 = None
    PlayerChoices2 = ["fice","funny","office"]
    print(" fice   funny office")
    while PlayerChoice2 not in PlayerChoices2 :
        PlayerChoice2 = input("What mad lib if you want to play ? ")
        if "fice" in PlayerChoice2:
            Noun = input("Enter a noun : ")
            Adjective4 = input("Enter a Adjective : ")
            Noun2 = input("Enter a noun : ")
            Adjective5 = input("Enter a Adjective : ")
            Noun3 = input("Enter a Noun : ")
            Verb = input("Enter a verb : ")
            Adjective6 = input("Enter a adjective : ")
            Noun4 = input("Enter a noun : ")
            Noun5 = input("Enter a noun : ")
            Adjective7 = input("Enter a adjective : ")
            Noun6 = input("Enter a noun : ")

            print("Hello there, fellow studnets of Meridian Elementary school.This is where you get to be creative, put in wacky phrases, and have fun! Today, you will be interviewing our school mascot,Thunder. Enjoy!")
            print("Lauren: Thunder, have you experienced some "+ Noun + " kids in your "+Adjective4+" career ? ")
            print("How does is feel to be the most "+Adjective5+" person in the "+Noun3)
            print("It definitely gets me "+Verb+"!")
            print("Do you like your "+Adjective6+" career ?")
            print("Yes,I do.I see "+Noun4+" learning every "+Noun5+".")
            print("Well we are "+Adjective7+" to "+Noun6+" that!")
            break
        
        if "funny" in PlayerChoice2:
            Adjective8 = input("Enter a adjective : ")
            FirstName = input("Enter a first name : ")
            PastTenseVerb = input("Enter a past tense verb : ")
            FirstName2 = input("Enter a first name : ")
            Adjective9 = input("Enter a Adjective : ")
            Adjective10 = input("Enter a adjective : ")
            PluralNoun = input("Enter a plural noun : ")
            LargeAnimal = input("Enter a large animal : ")
            SmallAnimal = input("Enter a small animal : ")
            AgirlName = input("Enter a girl name : ")
            Adjective11 = input("Enter a adjective : ")
            PluralNoun2 = input("Enter a plural Noun : ")
            Adjective12 = input("Enter a adjective : ")
            PluralNoun3 = input("Enter a plural noun : ")
            Number = int(input("Enter number 1-50 : "))
            FirstName3 = input("Enter first name's : ")
            NUmber2 = int(input("Enter a Number : "))
            PluralNoun4 = input("Enter a plural noun : ")
            Number3 = input("Enter a number : ")
            PluralNoun5 = input("Enter a plural noun : ")

            print("I, the "+Adjective8+"and"+Adjective9+FirstName+"has"+PastTenseVerb+FirstName+"s"+Adjective9+" sister and plans to steal her "+Adjective10+PluralNoun+"! What are a "+LargeAnimal+" and backpacking "+SmallAnimal+" Before you can help "+AgirlName+", you'll have to collect the "+Adjective11+PluralNoun2+" and "+Adjective12+PluralNoun3+" that open up the "+Number+" worlds connected to a "+FirstName3+" lair. There are "+NUmber2+PluralNoun4+" and "+Number3+PluralNoun5+" in the game,along with hundredes of other goodies for you to find.")

        if "office" in PlayerChoice2:
            ArticleOfClothing = input("Enter a article of clothing : ")
            Superlative = input("Enter a superlative : ")
            PluralNoun6 = input("Enter a plural noun : ")
            Sprot = input("Enter a sport : ")
            Noun7 = input("Enter a noun : ")
            PersonalTitle = input("Enter a personal title  : ")
            Adverb = input("Enter a adverb : ")
            ProperNoun = input("Enter proper noun : ")
            SongTitle = input("Enter a song title : ")
            Interjection = input("Enter a Interjection : ")
            ArticleOfClothing2 = input("Enter Article of clothing : ")
            Verb2 = input("Enter a verb : ")
            FamousPerson = input("Enter Famous person : ")
            PluralNoun7 = input("Enter a plural noun : ")
            PluralNoun8 = input("Enter a plural noun : ")
            ArticleOfClothing3 = input("Enter a article of clothing : ")
            Adjective13 = input("Enter a adjective : ")
            FieldOfStudy = input("Enter filed of study : ")

            print("I scoured my closet for the perfect "+ArticleOfClothing+" to wear.Dressing for the "+Superlative+" place around isn't easy.Sweating "+PluralNoun6+" during the interview is a sure sign of weakness. I must remember to play up my strength: "+Sprot+",menacing stares,and "+Noun7+" collecting.It has always been my dream to work with the Angel of Death, or "+PersonalTitle+" Devil.The power and prestige are "+Adverb+" Desirable.The Gates of "+ProperNoun+" tower above me as I ring the doorbell. I can't belive "+SongTitle+" is the doorbell chime."+Interjection+".his back "+ArticleOfClothing2+" looks better in person!")
            print("The Devil : Welcome to Hell. Your Interview will "+Verb2+" now.")
            print("Me : It's a pleasure to meet you. My name is "+FamousPerson+".")
            print("The Devil: Who cares? I have only one question. Do you hate "+PluralNoun7+" ?")
            print("Me : Yes,yes I do.I hate them more than "+PluralNoun8+".")
            print("The Devil: Your're hired.Wait,is that a "+ArticleOfClothing3+"you're wearing ? ")
            print("Me : No,it's actually a "+Adjective13+" suit.")
            print("The Devil: You're fired.Maybe you should pursue a career in "+FieldOfStudy+".")




 

